production:
  storage: mongodb://localhost:27017/khronos
  interval: 5
  controller:
    interval: 1
  runner:
    host: 'localhost'
    port: '7243'
  scheduler:
    host: 'localhost'
    port: '8080'

development:
  storage: mongodb://localhost:27017/khronos_development
  controller:
    interval: 1
  runner:
    host: 'localhost'
    port: '7243'
  scheduler:
    host: 'localhost'
    port: '8080'

test:
  storage: sqlite3://localhost/db/test.db
  controller:
    interval: 1
  runner:
    host: 'localhost'
    port: '7243'
  scheduler:
    host: 'localhost'
    port: '8080'
